'use client'

import Image from "next/image";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import devwilliam from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import consulting from '../public/consulting.png'
import code from '../public/code.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'

import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by ..." />
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>

      <main className="bg-whte px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        {/* Fill up whole screen */}
        <section className="min-h-screen">
          {/* On large screens, give 40 padding */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl">developedbywilliam</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              William Runyon
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Developer and Designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Super awesome Georgia Tech student
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          {/* margin x auto */}
          <div className="relative mx-auto overflow-hidden md:h-96 md:w-96 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20">
            {/* these properties are nextjs specific */}
            <Image src={devwilliam} layout="fill" objectFit="cover"/>
          </div>
        </section>
        {/* Section 2 */}

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the <span className="text-teal-500">beginning</span> of time I was awesome
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the <span className="text-teal-500">beginning</span> of time I was awesome
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} className="mx-auto" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p>
                Create elegant designs suited for your awesomeness
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} className="mx-auto" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Desings
              </h3>
              <p>
                Create elegant designs suited for your awesomeness
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} className="mx-auto" width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Desings
              </h3>
              <p>
                Create elegant designs suited for your awesomeness
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the <span className="text-teal-500">beginning</span> of time I was awesome
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the <span className="text-teal-500">beginning</span> of time I was awesome
            </p>
          </div>

          {/* Images */}
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web1}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"src={web2}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"src={web3}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"src={web4}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"src={web5}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"src={web6}/>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
